build:
	g++ -std=c++11 cpps/Node.cpp cpps/LinkedList.cpp cpps/Produs.cpp cpps/Palet.cpp cpps/Hashtable.cpp main.cpp cpps/Tranzactie.cpp cpps/Bon.cpp cpps/Categorie.cpp cpps/Magazin.cpp -o main

run:
	./main

clean:
	rm main Rezultate.csv	
